-- ============================================
-- Crear tabla notificaciones_pedidos_terminados
-- Almacena notificaciones temporales de pedidos terminados para todos los usuarios
-- ============================================

-- Crear la tabla notificaciones_pedidos_terminados
CREATE TABLE notificaciones_pedidos_terminados (
  -- Identificación
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  
  -- Referencias
  usuario_id UUID DEFAULT auth.uid() NOT NULL,
  cliente_id UUID,
  
  -- Información del pedido terminado
  mesa TEXT NOT NULL,
  productos JSONB NOT NULL, -- Array de objetos: [{producto, cantidad, unidad}, ...]
  
  -- Timestamps
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- ============================================
-- Crear índices para optimizar consultas
-- ============================================

-- Índice por cliente (más importante para mostrar notificaciones por cliente)
CREATE INDEX idx_notificaciones_cliente ON notificaciones_pedidos_terminados(cliente_id);

-- Índice por usuario (para filtrar por usuario)
CREATE INDEX idx_notificaciones_usuario ON notificaciones_pedidos_terminados(usuario_id);

-- Índice por fecha de creación (para ordenar cronológicamente)
CREATE INDEX idx_notificaciones_created_at ON notificaciones_pedidos_terminados(created_at DESC);

-- Índice compuesto: cliente + fecha (consulta más común)
CREATE INDEX idx_notificaciones_cliente_created ON notificaciones_pedidos_terminados(cliente_id, created_at DESC);

-- ============================================
-- Habilitar Row Level Security (RLS)
-- ============================================

ALTER TABLE notificaciones_pedidos_terminados ENABLE ROW LEVEL SECURITY;

-- ============================================
-- Crear políticas RLS
-- ============================================

-- Política: Los usuarios pueden VER todas las notificaciones de su cliente (para que todos vean)
CREATE POLICY "usuarios_pueden_ver_notificaciones_de_su_cliente" 
ON notificaciones_pedidos_terminados FOR SELECT 
USING (
  EXISTS (
    SELECT 1 FROM usuarios u
    WHERE u.usuario_id = auth.uid()
    AND u.cliente_id = notificaciones_pedidos_terminados.cliente_id
  )
);

-- Política: Los usuarios pueden INSERTAR notificaciones de su cliente
CREATE POLICY "usuarios_pueden_insertar_notificaciones" 
ON notificaciones_pedidos_terminados FOR INSERT 
WITH CHECK (
  auth.uid() = usuario_id
  AND EXISTS (
    SELECT 1 FROM usuarios u
    WHERE u.usuario_id = auth.uid()
    AND u.cliente_id = cliente_id
  )
);

-- Política: Los usuarios pueden ACTUALIZAR (marcar como visto) notificaciones de su cliente
CREATE POLICY "usuarios_pueden_actualizar_notificaciones" 
ON notificaciones_pedidos_terminados FOR UPDATE 
USING (
  EXISTS (
    SELECT 1 FROM usuarios u
    WHERE u.usuario_id = auth.uid()
    AND u.cliente_id = notificaciones_pedidos_terminados.cliente_id
  )
);

-- Política: Los usuarios pueden ELIMINAR notificaciones de su cliente
CREATE POLICY "usuarios_pueden_eliminar_notificaciones" 
ON notificaciones_pedidos_terminados FOR DELETE 
USING (
  EXISTS (
    SELECT 1 FROM usuarios u
    WHERE u.usuario_id = auth.uid()
    AND u.cliente_id = notificaciones_pedidos_terminados.cliente_id
  )
);

-- ============================================
-- Habilitar Realtime (Tiempo Real)
-- ============================================

-- Agregar la tabla a la publicación de Realtime
ALTER PUBLICATION supabase_realtime ADD TABLE notificaciones_pedidos_terminados;

-- ============================================
-- VERIFICACIÓN: Consultar estructura creada
-- ============================================

SELECT 
    column_name,
    data_type,
    column_default,
    is_nullable
FROM information_schema.columns 
WHERE table_name = 'notificaciones_pedidos_terminados'
ORDER BY ordinal_position;

